USE Todo;

CREATE TABLE IF NOT EXISTS TodoItem (
    Id BIGINT NOT NULL PRIMARY KEY,
    CreatedOn DATETIME NOT NULL,    
    UpdatedOn DATETIME NOT NULL,
    Name VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL,
    Status VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;